Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace mission09_jrencher.Models
{
    public partial class Book
    {
        [Key]
        [Required]
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Isbn { get; set; }
        public string Classification { get; set; }
        public string Category { get; set; }
        public int PageCount { get; set; }
        public double Price { get; set; }
    }
}

Models/BookstoreContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace mission09_jrencher.Models
{
    public class BookstoreContext : DbContext
    {
        public BookstoreContext()
        {
        }

        public BookstoreContext(DbContextOptions<BookstoreContext> options)
            : base(options)
        {
        }

        public DbSet<Book> Books { get; set; }
        
    }
}

Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_jrencher.Models
{
    public class Cart
    {
        public List<CartLineItem> Items { get; set; } = new List<CartLineItem>();

        public virtual void AddItem (Book book, int qty)
        {
            CartLineItem line = Items
                .Where(b => b.Book.BookId == book.BookId)
                .FirstOrDefault();

            if (line == null)
            {
                Items.Add(new CartLineItem
                {
                    Book = book,
                    Quantity = qty

                });
            }
            else
            {
                line.Quantity += qty;
            }
        }

        public virtual void RemoveItem (Book book)
        {
            Items.RemoveAll(x => x.Book.BookId == book.BookId);
        }

        public virtual void ClearBasket()
        {
            Items.Clear();
        }

        public virtual double CalculateTotal()
        {
            var sum = Items.Sum(x => x.Quantity * 25);

            return sum;
        }

    }

    

    public class CartLineItem
    {
        public int LineID { get; set; }
        public Book Book { get; set; }
        public int Quantity { get; set; }
    }
}

Models/EFBookstoreRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_jrencher.Models
{
    public class EFBookstoreRepository : IBookstoreRepository
    {
        private BookstoreContext context { get; set; }

        public EFBookstoreRepository (BookstoreContext temp)
        {
            context = temp;
        }
        public IQueryable<Book> Books => context.Books;
    }
}

Models/IBookstoreRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_jrencher.Models
{
    public interface IBookstoreRepository
    {
        IQueryable<Book> Books { get; }
    }
}

Models/SessionCart.cs
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using mission09_jrencher.Infastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace mission09_jrencher.Models
{
    public class SessionCart : Cart
    {
        public static Cart GetCart (IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            SessionCart cart = session?.GetJson<SessionCart>("Cart") ?? new SessionCart();

            return cart;
        }

        [JsonIgnore]
        public ISession Session { get; set; }

        public override void AddItem(Book book, int qty)
        {
            base.AddItem(book, qty);
            Session.SetJson("Cart", this);
        }

        public override void RemoveItem(Book book)
        {
            base.RemoveItem(book);
            Session.SetJson("Cart", this);
        }

        public override void ClearBasket()
        {
            base.ClearBasket();
            Session.Remove("Cart");
        }
    }
}

Models/ViewModels/PageInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_jrencher.Models.ViewModels
{
    public class PageInfo
    {
        public int TotalNumBooks { get; set; }

        public int BooksPerPage { get; set; }

        public int CurrentPage { get; set; }

        //Calculate how many pages we need.
        public int TotalPages => (int) Math.Ceiling((double) TotalNumBooks / BooksPerPage);
    }
}

Models/ViewModels/ProjectsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_jrencher.Models.ViewModels
{
    public class ProjectsViewModel
    {
        public IQueryable<Book> Book { get; set; }

        public PageInfo PageInfo { get; set; }
    }
}

Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission09_jrencher.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_jrencher.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["catetoryType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using mission09_jrencher.Models;
using mission09_jrencher.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_jrencher.Controllers
{
    public class HomeController : Controller
    {
        private IBookstoreRepository repo;

        public HomeController (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IActionResult Index(string categoryType, int pageNum = 1)
        {
            //Num Books Per Page
            int pageSize = 10;

            //Organizes the List of Books
            var x = new ProjectsViewModel
            {
                Book = repo.Books
                //Allows us to filter by Category
                .Where(b => b.Category == categoryType || categoryType == null)
                .OrderBy(b => b.Title)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumBooks = 
                        (categoryType == null 
                        ? repo.Books.Count() 
                        : repo.Books.Where(x => x.Category == categoryType).Count()),
                    BooksPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };

            return View(x);
        }
    }
}

Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using mission09_jrencher.Infastructure;
using mission09_jrencher.Models;

namespace mission09_jrencher.Pages
{
    public class CartModel : PageModel
    {

        private IBookstoreRepository repo { get; set; }

        public CartModel (IBookstoreRepository temp)
        {
            repo = temp;
        }
        public Cart cart { get; set; }

        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            cart.AddItem(b, 1);

            HttpContext.Session.SetJson("cart", cart);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Pages/Cart.cshtml
@page
@model mission09_jrencher.Pages.CartModel
@{
}

<h2>My Cart</h2>

@*Custom CSS #1 - Dark Mode Table :), Custom CSS #2 - Highlights Row On Hover*@
<table class="table table-dark table-hover table-bordered table-striped">

    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach(var i in Model.cart.Items)
            {
                <tr>
                    <td>@i.Book.Title</td>
                    <td>@i.Quantity</td>
                    <td>$25.00</td>
                    <td>@((i.Quantity * 25).ToString("c"))</td>
                </tr>
            }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>

</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>

Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p=2">
        <span class="navbar-brand m-lg-2">Bookstore</span>
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>

Views/Home/Index.cshtml
@{
}

@model ProjectsViewModel

@foreach (Book b in Model.Book)
{
    <partial name="StoreSummary" model="b"/>
}

<div page-model="@Model.PageInfo" page-action="Index" page-class="btn"
     page-class-normal="btn-outline-dark" page-class-selected="btn-primary" page-class-enabled="true"
     class="btn-group pull-right m-1"></div>

Views/Shared/Components/Types/Default.cshtml
@{
}

@model IEnumerable<string>

    <div class="d-grid gap-2">
        <a asp-controller="Home" asp-action="Index" asp-route-categoryType="" asp-route-pageNum="1" class="btn  btn-outline-secondary">Home</a>

        @foreach (string b in Model)
        {
            <a asp-controller="Home" asp-action="Index" asp-route-categoryType="@b" asp-route-pageNum="1"
               class="btn @(ViewBag.SelectedType == b ? "btn-primary" : "btn-outline-secondary")">@b</a>
        }
    </div>

Views/Shared/StoreSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4 class="text-capitalize">@Model.Title</h4>

        <span class="badge bg-info" style="float:right">
            Price: $@Model.Price
        </span>
    </div>
    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Page Count: @Model.PageCount</li>
    </ul>

    <form method="post" asp-page="/Cart">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Buy Now</button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p=2">
         <span class="navbar-brand m-lg-2">Bookstore</span>
    </div>

    <div class="row m-1 p-1">

        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>
            <div class="col-9">
                <div>
                    @RenderBody()
                </div>
            </div>
    </div>


</body>
</html>